import { StyleSheet } from 'react-native';

export const getStyles = (isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
  },
  networkHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#334155'
  },
  serverDetails: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8
  },
  serverText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12
  },
  settingsBtn: {
    padding: 2
  },
  settingsBtnText: {
    fontSize: 14
  },
  loginContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
  },
  roleSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 10,
    marginBottom: 8,
  },
  roleEmoji: {
    fontSize: 32,
  },
  roleBtnTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
  },
  roleBtnSub: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  loginHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  loginBackBtn: {
    padding: 4,
  },
  loginTitleText: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 18,
    fontWeight: 'bold',
  },
  loginModeTabs: {
    flexDirection: 'row',
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    borderRadius: 8,
    padding: 4,
    marginVertical: 12,
  },
  loginModeTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  loginModeTabActive: {
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
  },
  loginModeTabText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
    fontWeight: 'bold',
  },
  loginModeTabTextActive: {
    color: isDark ? '#FFF' : '#0F172A',
  },
  sendOtpBtn: {
    paddingHorizontal: 12,
    justifyContent: 'center',
    borderRadius: 8,
    height: 48,
  },
  sendOtpBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  demoAccountsCard: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    marginTop: 20,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  demoAccountsTitle: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  demoAccountRow: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 11,
    lineHeight: 16,
  },
  appTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  appSubtitle: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 30,
  },
  card: {
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
    marginBottom: 15,
  },
  cardTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  userBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    padding: 15,
    borderRadius: 8,
    marginBottom: 12,
  },
  ownerBtnBorder: {
    borderWidth: 1.5,
    borderColor: '#6366F1',
  },
  memberBtnBorder: {
    borderWidth: 1.5,
    borderColor: '#10B981',
  },
  userBtnName: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: '600',
  },
  userBtnRole: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: isDark ? '#0F172A' : '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1E293B' : '#E2E8F0',
  },
  headerProfileSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerWelcome: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
    fontWeight: '500',
  },
  headerUser: {
    color: isDark ? '#FFFFFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerRoleBadge: {
    backgroundColor: isDark ? '#1E293B' : '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 2,
    alignSelf: 'flex-start',
  },
  headerRoleBadgeText: {
    color: isDark ? '#38BDF8' : '#0284C7',
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  switchRoleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#311010' : '#FEE2E2',
    borderWidth: 1,
    borderColor: isDark ? '#7F1D1D' : '#FCA5A5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  switchRoleText: {
    color: isDark ? '#FCA5A5' : '#EF4444',
    fontSize: 12,
    fontWeight: 'bold',
  },
  metricsRow: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  metricCard: {
    flex: 1,
    marginHorizontal: 4,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  metricLabel: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 10,
    marginBottom: 4,
  },
  metricVal: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 12,
  },
  sectionTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 18,
    fontWeight: 'bold',
  },
  createChitBtn: {
    backgroundColor: '#6366F1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  createChitText: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 12,
    fontWeight: 'bold',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 15,
  },
  chitCard: {
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  chitCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  chitCardName: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  statusBadgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  chitCardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#334155' : '#E2E8F0',
    paddingBottom: 12,
    marginBottom: 10,
  },
  cardLabel: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 10,
    marginBottom: 4,
  },
  cardValue: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 14,
    fontWeight: 'bold',
  },
  chitCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerInfoText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
  },
  viewDetailsText: {
    color: '#818CF8',
    fontSize: 12,
    fontWeight: 'bold',
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#334155'
  },
  backBtn: {
    padding: 4
  },
  backBtnText: {
    color: '#818CF8',
    fontSize: 14,
    fontWeight: '600'
  },
  detailChitName: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
    maxWidth: '70%'
  },
  tabsRow: {
    flexDirection: 'row',
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#334155'
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
  },
  activeTabBtn: {
    borderBottomWidth: 2,
    borderBottomColor: '#6366F1',
  },
  tabBtnText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 10,
    fontWeight: 'bold',
  },
  activeTabBtnText: {
    color: isDark ? '#FFF' : '#0F172A',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#334155' : '#E2E8F0',
  },
  infoLabel: {
    color: isDark ? '#94A3B8' : '#64748B',
  },
  infoVal: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: 'bold',
  },
  liveAuctionCard: {
    marginTop: 20,
    borderRadius: 8,
    padding: 15,
    borderWidth: 1.5,
    borderColor: '#4F46E5',
  },
  liveAuctionCardTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  liveAuctionCardSub: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
    marginBottom: 15,
  },
  actionBtn: {
    backgroundColor: '#6366F1',
    padding: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  actionBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  memberListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#334155' : '#E2E8F0',
  },
  memberNo: {
    color: '#818CF8',
    fontSize: 16,
    fontWeight: 'bold',
    width: 30,
  },
  memberName: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: '600',
  },
  memberPhone: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
  },
  historyCard: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  historyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#334155' : '#E2E8F0',
    paddingBottom: 6,
  },
  historyMonth: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: 'bold',
  },
  historyStatus: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  historyDetail: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 13,
    marginBottom: 8,
  },
  bold: {
    fontWeight: 'bold',
    color: isDark ? '#FFF' : '#0F172A',
  },
  historyGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  historyVal: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: 'bold',
    fontSize: 12,
    marginTop: 2,
  },
  emptyText: {
    color: isDark ? '#94A3B8' : '#64748B',
    textAlign: 'center',
    marginVertical: 30,
  },
  payBtn: {
    backgroundColor: '#10B981',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
  },
  payBtnText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  paymentCard: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  paymentMember: {
    color: isDark ? '#FFF' : '#0F172A',
    fontWeight: 'bold',
  },
  paymentBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  paymentInfo: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: isDark ? '#334155' : '#E2E8F0',
    paddingTop: 8,
  },
  actionBtnSec: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
  },
  actionBtnSecText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  disbursalCard: {
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    padding: 15,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#10B981',
  },
  disbursalCardTitle: {
    color: '#10B981',
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 8,
  },
  disbursalCardText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
    marginBottom: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
    overflow: 'hidden',
  },
  settingsModal: {
    width: '85%',
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  settingsTip: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
    marginTop: 8,
    marginBottom: 15,
    lineHeight: 15,
  },
  auctionModalContainer: {
    width: '95%',
    height: '90%',
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#334155' : '#E2E8F0',
  },
  modalTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 18,
    fontWeight: 'bold',
  },
  closeBtn: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 20,
    fontWeight: 'bold',
  },
  formScroll: {
    padding: 20,
  },
  auctionRoomScroll: {
    padding: 15,
  },
  inputLabel: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    color: isDark ? '#FFF' : '#0F172A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
    fontSize: 14,
    marginBottom: 10,
  },
  submitBtn: {
    backgroundColor: '#6366F1',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  submitBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  amountBanner: {
    color: '#10B981',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
  },
  radioRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 15,
  },
  radioBtn: {
    flex: 1,
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  radioBtnActive: {
    borderColor: '#10B981',
    backgroundColor: '#064E3B',
  },
  radioText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontWeight: 'bold',
  },
  radioTextActive: {
    color: isDark ? '#FFF' : '#0F172A',
  },
  timerContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  timeLeftLabel: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
  },
  timeLeftValue: {
    fontSize: 32,
    fontWeight: 'bold',
  },
  bidBanner: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#F59E0B',
    marginBottom: 15,
  },
  bidBannerLabel: {
    color: '#F59E0B',
    fontSize: 13,
    fontWeight: 'bold',
  },
  bidBannerValue: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 28,
    fontWeight: 'bold',
    marginVertical: 4,
  },
  bidBannerWinner: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
  },
  calculationPreview: {
    backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
    marginBottom: 20,
  },
  calcTitle: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
  },
  calcValue: {
    color: '#10B981',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 2,
  },
  biddingControl: {
    backgroundColor: isDark ? '#0F172A' : '#F8FAFC',
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  bidInputLabel: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  submitBidBtn: {
    backgroundColor: '#F59E0B',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  submitBidBtnText: {
    color: '#0F172A',
    fontWeight: 'bold',
    fontSize: 14,
  },
  lotteryContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  lotteryTitle: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  lotterySub: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 12,
    marginTop: 6,
    textAlign: 'center',
    marginBottom: 25,
  },
  spinningWheel: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 8,
    borderColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  wheelSegment1: {
    position: 'absolute',
    width: '100%',
    height: '50%',
    backgroundColor: '#4F46E5',
    top: 0,
  },
  wheelSegment2: {
    position: 'absolute',
    width: '100%',
    height: '50%',
    backgroundColor: '#10B981',
    bottom: 0,
  },
  winnerAnnounce: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 15,
  },
  winnerBidText: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 14,
    marginVertical: 10,
  },
  // Sidebar styles
  sidebarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    flexDirection: 'row',
  },
  sidebarContainer: {
    width: '78%',
    maxWidth: 320,
    height: '100%',
    backgroundColor: isDark ? '#0F172A' : '#FFFFFF',
    borderRightWidth: 1,
    borderRightColor: isDark ? '#1E293B' : '#E2E8F0',
    paddingTop: 40,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 10,
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1E293B' : '#E2E8F0',
  },
  sidebarTitle: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 18,
    fontWeight: 'bold',
  },
  sidebarCloseBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: isDark ? '#1E293B' : '#F1F5F9',
  },
  sidebarCloseText: {
    fontSize: 14,
    color: isDark ? '#94A3B8' : '#64748B',
    fontWeight: 'bold',
  },
  sidebarProfile: {
    backgroundColor: isDark ? '#1E293B' : '#F8FAFC',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#E2E8F0',
  },
  sidebarProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sidebarAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  sidebarAvatarText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sidebarName: {
    color: isDark ? '#FFF' : '#0F172A',
    fontSize: 14,
    fontWeight: 'bold',
    flex: 1,
  },
  sidebarRoleText: {
    color: isDark ? '#38BDF8' : '#0284C7',
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  sidebarPhone: {
    color: isDark ? '#94A3B8' : '#64748B',
    fontSize: 11,
  },
  sidebarNavItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 4,
  },
  sidebarNavItemActive: {
    backgroundColor: isDark ? '#1E1B4B' : '#EEF2F6',
  },
  sidebarNavIcon: {
    fontSize: 16,
    marginRight: 12,
  },
  sidebarNavText: {
    color: isDark ? '#E2E8F0' : '#334155',
    fontSize: 13,
    fontWeight: '600',
  },
  sidebarNavTextActive: {
    color: '#6366F1',
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: isDark ? '#1E293B' : '#E2E8F0',
    marginVertical: 15,
  },
  sidebarCalcTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6366F1',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  sidebarCalcInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sidebarCalcLabel: {
    flex: 1.2,
    fontSize: 11,
    color: isDark ? '#94A3B8' : '#64748B',
  },
  sidebarCalcInput: {
    flex: 1,
    backgroundColor: isDark ? '#1E293B' : '#F1F5F9',
    borderColor: isDark ? '#334155' : '#CBD5E1',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    color: isDark ? '#FFF' : '#000',
  },
  sidebarCalcResult: {
    backgroundColor: isDark ? '#111827' : '#F8FAFC',
    padding: 10,
    borderRadius: 6,
    marginTop: 8,
    borderWidth: 1,
    borderColor: isDark ? '#1E293B' : '#E2E8F0',
  },
  sidebarCalcResultText: {
    fontSize: 10,
    color: isDark ? '#E2E8F0' : '#334155',
    marginBottom: 4,
  },
});
